name: Build in Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build:
    name: "Build in Docker"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: "Build image"
        run: docker build --no-cache .
